# Build the Zybo Z7-20 DMA GEMV bitstream and export an XSA.
#
# This is the long-running S02 build entrypoint. It is created during S01 but
# intentionally not run by S01-only agents.
#
# Recommended shell wrapper:
#   nohup /opt/Xilinx/Vivado/2024.2/bin/vivado -mode batch \
#     -source scripts/build_zybo_gemv_dma_bitstream.tcl \
#     > logs/vivado_dma_build_console.log 2>&1 &

error "DEPRECATED by S01.5: do not build hw/zybo_gemv_dma. Use scripts/build_gptalk_dma_bitstream.tcl with hw/vivado_project/GPTalk.xpr."

set script_dir [file normalize [file dirname [info script]]]
set repo_root [file normalize [file join $script_dir ..]]
set log_dir [file join $repo_root logs]
set report_dir [file join $repo_root reports]
file mkdir $log_dir
file mkdir $report_dir

source [file join $repo_root scripts create_zybo_gemv_dma_hw.tcl]

set build_failed 0

launch_runs synth_1 -jobs 8
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    set build_failed 1
    puts "ERROR: synth_1 did not complete"
}
if {[get_property STATUS [get_runs synth_1]] ne "synth_design Complete!"} {
    set build_failed 1
    puts "ERROR: synth_1 failed: [get_property STATUS [get_runs synth_1]]"
}

if {$build_failed} {
    source [file join $repo_root scripts report_failed_impl.tcl]
    error "synthesis failed"
}

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    set build_failed 1
    puts "ERROR: impl_1 did not complete"
}
if {![string match "*Complete*" [get_property STATUS [get_runs impl_1]]]} {
    set build_failed 1
    puts "ERROR: impl_1 failed: [get_property STATUS [get_runs impl_1]]"
}

if {$build_failed} {
    source [file join $repo_root scripts report_failed_impl.tcl]
    error "implementation failed"
}

set bit_file [file join $out_dir zybo_gemv_dma.runs impl_1 ${bd_name}_wrapper.bit]
set export_dir [file join $out_dir export]
file mkdir $export_dir
set xsa_file [file join $export_dir zybo_gemv_dma.xsa]
write_hw_platform -fixed -include_bit -force -file $xsa_file

set result_doc [file join $repo_root docs hw_dma_bringup_result.md]
set result_fd [open $result_doc w]
puts $result_fd "# DMA GEMV Hardware Bring-Up Result"
puts $result_fd ""
puts $result_fd "Generated by `scripts/build_zybo_gemv_dma_bitstream.tcl`."
puts $result_fd ""
puts $result_fd "- Bitstream: `$bit_file`"
puts $result_fd "- XSA: `$xsa_file`"
puts $result_fd [format "- GEMV control base: `0x%08X`" $gemv_base]
puts $result_fd [format "- AXI DMA base: `0x%08X`" $dma_base]
puts $result_fd [format "- Input BRAM base: `0x%08X`" $bram_base]
puts $result_fd "- Input/output buffer method: input vector in AXI BRAM, weight/scale through DMA MM2S, results through DMA S2MM."
close $result_fd

puts "BIT_FILE=$bit_file"
puts "XSA_FILE=$xsa_file"
puts [format "GEMV_CONTROL_BASE=0x%08X" $gemv_base]
puts [format "AXI_DMA_BASE=0x%08X" $dma_base]
puts [format "INPUT_BRAM_BASE=0x%08X" $bram_base]
puts "RESULT_DOC=$result_doc"
