# Create Zybo Z7-20 hardware with PS7 + AXI-Lite GEMV smoke register IP.
#
# This is the bring-up fallback used when the full GEMV datapath cannot be
# routed quickly enough. It proves PS-to-PL AXI-Lite access to the GEMV register
# window so Linux C/devmem can read VERSION/STATUS at the documented base.
#
# Run:
#   vivado -mode batch -source scripts/create_zybo_gemv_smoke_hw.tcl
#
# Outputs:
#   hw/zybo_gemv_smoke/zybo_gemv_smoke.runs/impl_1/design_1_wrapper.bit
#   hw/zybo_gemv_smoke/export/zybo_gemv_smoke.xsa
#   logs/hw_smoke_address_map.txt

set script_dir [file normalize [file dirname [info script]]]
set repo_root [file normalize [file join $script_dir ..]]
set out_dir [file join $repo_root hw zybo_gemv_smoke]
set log_dir [file join $repo_root logs]
file mkdir $log_dir

set board_repo [file join $repo_root vivado_board_files digilent-vivado-boards new board_files]
if {[file exists $board_repo]} {
    set_param board.repoPaths [list $board_repo]
}

set board_part "digilentinc.com:zybo-z7-20:part0:1.2"
set part_name "xc7z020clg400-1"
set bd_name "design_1"
set gemv_base 0x43C00000

set rtl_smoke [file join $repo_root vivado_ip rtl gemv_q8_0_axi_lite_smoke.v]
if {![file exists $rtl_smoke]} {
    error "missing RTL file: $rtl_smoke"
}

file delete -force $out_dir
create_project zybo_gemv_smoke $out_dir -part $part_name
set_property board_part $board_part [current_project]
set_property target_language Verilog [current_project]

add_files -norecurse -fileset sources_1 [list $rtl_smoke]
set_property file_type Verilog [get_files $rtl_smoke]
update_compile_order -fileset sources_1

create_bd_design $bd_name
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 processing_system7_0
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1" Master "Disable" Slave "Disable"} \
    [get_bd_cells processing_system7_0]
set_property -dict [list \
    CONFIG.PCW_USE_M_AXI_GP0 {1} \
    CONFIG.PCW_EN_CLK0_PORT {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
] [get_bd_cells processing_system7_0]

create_bd_cell -type module -reference gemv_q8_0_axi_lite_smoke gemv_q8_0_axi_lite_smoke_0

connect_bd_net [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins gemv_q8_0_axi_lite_smoke_0/S_AXI_ACLK]
connect_bd_net [get_bd_pins processing_system7_0/FCLK_RESET0_N] [get_bd_pins gemv_q8_0_axi_lite_smoke_0/S_AXI_ARESETN]

apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Master "/processing_system7_0/M_AXI_GP0" Slave "/gemv_q8_0_axi_lite_smoke_0/S_AXI" intc_ip "New AXI Interconnect" Clk_master "/processing_system7_0/FCLK_CLK0" Clk_slave "/processing_system7_0/FCLK_CLK0" Clk_xbar "/processing_system7_0/FCLK_CLK0"} \
    [get_bd_intf_pins gemv_q8_0_axi_lite_smoke_0/S_AXI]

assign_bd_address
set gemv_segs [get_bd_addr_segs -quiet -regexp {.*SEG_gemv_q8_0_axi_lite_smoke_0.*}]
if {[llength $gemv_segs] == 0} {
    error "could not find GEMV smoke AXI address segment"
}
foreach seg $gemv_segs {
    set_property offset $gemv_base $seg
    set_property range 4K $seg
}

validate_bd_design
save_bd_design

set address_report [file join $log_dir hw_smoke_address_map.txt]
set addr_fd [open $address_report w]
puts $addr_fd "Zybo Z7-20 GEMV smoke address map"
puts $addr_fd "Generated by scripts/create_zybo_gemv_smoke_hw.tcl"
puts $addr_fd ""
foreach seg [get_bd_addr_segs -quiet -regexp {.*SEG_.*}] {
    puts $addr_fd [format "%s OFFSET=%s RANGE=%s" $seg [get_property OFFSET $seg] [get_property RANGE $seg]]
}
close $addr_fd

set bd_file [get_files [file join $out_dir zybo_gemv_smoke.srcs sources_1 bd $bd_name ${bd_name}.bd]]
make_wrapper -files $bd_file -top
add_files -norecurse [file join $out_dir zybo_gemv_smoke.gen sources_1 bd $bd_name hdl ${bd_name}_wrapper.v]
set_property top ${bd_name}_wrapper [current_fileset]
update_compile_order -fileset sources_1

launch_runs synth_1 -jobs 8
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    error "synth_1 did not complete"
}
if {[get_property STATUS [get_runs synth_1]] ne "synth_design Complete!"} {
    error "synth_1 failed: [get_property STATUS [get_runs synth_1]]"
}

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    error "impl_1 did not complete"
}
if {![string match "*Complete*" [get_property STATUS [get_runs impl_1]]]} {
    error "impl_1 failed: [get_property STATUS [get_runs impl_1]]"
}

set bit_file [file join $out_dir zybo_gemv_smoke.runs impl_1 ${bd_name}_wrapper.bit]
set export_dir [file join $out_dir export]
file mkdir $export_dir
set xsa_file [file join $export_dir zybo_gemv_smoke.xsa]
write_hw_platform -fixed -include_bit -force -file $xsa_file

puts "BIT_FILE=$bit_file"
puts "XSA_FILE=$xsa_file"
puts [format "GEMV_BASE=0x%08X" $gemv_base]
puts "ADDRESS_REPORT=$address_report"
